export const FIELD_META = {
  projectName: { label: "Project Name" },
  clientName: { label: "Client Name" },
  location: { label: "Location" },
  preparedBy: { label: "Prepared By" },
  date: { label: "Date" },
  roomName: { label: "Room Name" },
  roomClass: { label: "Room Class" },
  application: { label: "Application" },
  designStandard: { label: "Design Standard" },
  construction: { label: "Construction" },
  filtration: { label: "Filtration" },
  coilType: { label: "Coil Type" },
  powerSupply: { label: "Power Supply" },

  project_name: { label: "Project Name" },
  client_name: { label: "Client Name" },
  airflow_cfm: { label: "Air Flow", unit: "CFM" },
  cooling_tr: { label: "Cooling Load", unit: "TR" },

  roomLength: { label: "Room Length", unit: "m" },
  roomWidth: { label: "Room Width", unit: "m" },
  roomHeight: { label: "Room Height", unit: "m" },
  roomArea: { label: "Room Area", unit: "m²" },
  roomVolume: { label: "Room Volume", unit: "m³" },

  peopleCount: { label: "People Count", unit: "Nos" },
  lightingLoad: { label: "Lighting Load", unit: "W" },
  lightingWatt: { label: "Lighting Load", unit: "W" },
  equipmentLoad: { label: "Equipment Load", unit: "W" },
  equipmentWatt: { label: "Equipment Load", unit: "W" },
  freshAirCFM: { label: "Fresh Air", unit: "CFM" },
  outdoorTemp: { label: "Outdoor Temperature", unit: "°C" },
  indoorTemp: { label: "Indoor Temperature", unit: "°C" },
  roomTemperature: { label: "Room Temperature", unit: "°C" },
  relativeHumidity: { label: "Relative Humidity", unit: "%" },
  freshAirPercent: { label: "Fresh Air", unit: "%" },
  uValue: { label: "U Value", unit: "W/m²·K" },
  wallU: { label: "Wall U Value", unit: "W/m²·K" },
  roofU: { label: "Roof U Value", unit: "W/m²·K" },
  glassU: { label: "Glass U Value", unit: "W/m²·K" },
  wallArea: { label: "Wall Area", unit: "m²" },
  roofArea: { label: "Roof Area", unit: "m²" },
  glassArea: { label: "Glass Area", unit: "m²" },
  deltaT: { label: "Temperature Difference", unit: "K" },
  solarFactor: { label: "Solar Heat Gain Factor", unit: "W/m²" },
  peopleSensible: { label: "People Sensible Load", unit: "W" },
  peopleLatent: { label: "People Latent Load", unit: "W" },
  lightingHeat: { label: "Lighting Heat", unit: "W" },
  equipmentHeat: { label: "Equipment Heat", unit: "W" },
  wallHeat: { label: "Wall Heat Gain", unit: "W" },
  roofHeat: { label: "Roof Heat Gain", unit: "W" },
  glassTransmission: { label: "Glass Transmission Load", unit: "W" },
  solarHeatGain: { label: "Solar Heat Gain", unit: "W" },
  freshAirSensible: { label: "Fresh Air Sensible Load", unit: "W" },
  freshAirLatent: { label: "Fresh Air Latent Load", unit: "W" },
  totalSensible: { label: "Total Sensible Heat", unit: "W" },
  totalLatent: { label: "Total Latent Heat", unit: "W" },
  grandTotalHeat: { label: "Grand Total Heat", unit: "W" },
  totalTR: { label: "Total Cooling Load", unit: "TR" },
  safetyTR: { label: "Cooling Load With Safety", unit: "TR" },
  supplyCFM: { label: "Recommended Supply Air", unit: "CFM" },
  SHR: { label: "Sensible Heat Ratio" },

  dryBulbTemp: { label: "Dry Bulb Temperature", unit: "°C" },
  wetBulbTemp: { label: "Wet Bulb Temperature", unit: "°C" },
  atmosphericPressure: { label: "Atmospheric Pressure", unit: "kPa" },
  saturationPressure: { label: "Saturation Pressure", unit: "kPa" },
  vaporPressure: { label: "Vapor Pressure", unit: "kPa" },
  humidityRatio: { label: "Humidity Ratio", unit: "g/kg dry air" },
  enthalpy: { label: "Enthalpy", unit: "kJ/kg dry air" },
  dewPoint: { label: "Dew Point", unit: "°C" },
  specificVolume: { label: "Specific Volume", unit: "m³/kg" },
  airDensity: { label: "Air Density", unit: "kg/m³" },
  apparatusDewPoint: { label: "Apparatus Dew Point", unit: "°C" },
  sensibleHeatFactor: { label: "Sensible Heat Factor" },
  roomSHF: { label: "Room SHF" },
  grandSHF: { label: "Grand SHF" },

  airFlowCFM: { label: "Air Flow", unit: "CFM" },
  airFlowM3s: { label: "Air Flow", unit: "m³/s" },
  airFlowCMH: { label: "Air Flow", unit: "CMH" },
  airMassFlow: { label: "Air Mass Flow", unit: "kg/s" },
  enteringDBT: { label: "Entering DBT", unit: "°C" },
  leavingDBT: { label: "Leaving DBT", unit: "°C" },
  enteringWBT: { label: "Entering WBT", unit: "°C" },
  leavingWBT: { label: "Leaving WBT", unit: "°C" },
  enteringAirTemp: { label: "Entering Air Temperature", unit: "°C" },
  leavingAirTemp: { label: "Leaving Air Temperature", unit: "°C" },
  enteringRH: { label: "Entering RH", unit: "%" },
  leavingRH: { label: "Leaving RH", unit: "%" },
  chilledWaterIn: { label: "Chilled Water Inlet", unit: "°C" },
  chilledWaterOut: { label: "Chilled Water Outlet", unit: "°C" },
  faceVelocity: { label: "Face Velocity", unit: "m/s" },
  finSpacing: { label: "Fin Spacing", unit: "FPI" },
  rows: { label: "Coil Rows", unit: "Nos" },
  sensibleHeat: { label: "Sensible Heat", unit: "W" },
  latentHeat: { label: "Latent Heat", unit: "W" },
  totalCooling: { label: "Total Cooling", unit: "W" },
  waterFlowLPM: { label: "Water Flow", unit: "LPM" },
  faceArea: { label: "Face Area", unit: "m²" },
  coilWidth: { label: "Coil Width", unit: "m" },
  coilHeight: { label: "Coil Height", unit: "m" },
  bypassFactor: { label: "Bypass Factor" },
  airPressureDrop: { label: "Air Pressure Drop", unit: "Pa" },
  waterPressureDrop: { label: "Water Pressure Drop", unit: "kPa" },
  tubeVelocity: { label: "Tube Velocity", unit: "m/s" },
  coilEfficiency: { label: "Coil Efficiency", unit: "%" },
  lmtd: { label: "LMTD", unit: "K" },

  filterPD: { label: "Filter Pressure Drop", unit: "Pa" },
  coilPD: { label: "Coil Pressure Drop", unit: "Pa" },
  ductPD: { label: "Duct Pressure Drop", unit: "Pa" },
  diffuserPD: { label: "Diffuser Pressure Drop", unit: "Pa" },
  totalStaticPressure: { label: "Total Static Pressure", unit: "Pa" },
  fanEfficiency: { label: "Fan Efficiency", unit: "%" },
  motorEfficiency: { label: "Motor Efficiency", unit: "%" },
  driveEfficiency: { label: "Drive Efficiency", unit: "%" },
  safetyFactor: { label: "Safety Factor" },
  rpm: { label: "Fan Speed", unit: "RPM" },
  outletArea: { label: "Fan Outlet Area", unit: "m²" },
  airPower: { label: "Air Power", unit: "W" },
  shaftPower: { label: "Shaft Power", unit: "W" },
  motorPowerKW: { label: "Motor Power", unit: "kW" },
  motorPowerHP: { label: "Motor Power", unit: "HP" },
  brakeHorsePower: { label: "Brake Horse Power", unit: "HP" },
  outletVelocity: { label: "Outlet Velocity", unit: "m/s" },
  systemResistance: { label: "System Resistance" },
  fanClass: { label: "Fan Class" },
  driveType: { label: "Drive Type" },

  velocity: { label: "Duct Velocity", unit: "m/s" },
  ductVelocity: { label: "Duct Velocity", unit: "m/s" },
  ductLength: { label: "Duct Length", unit: "m" },
  roughness: { label: "Duct Roughness", unit: "mm" },
  ductArea: { label: "Duct Area", unit: "m²" },
  ductWidthMM: { label: "Duct Width", unit: "mm" },
  ductHeightMM: { label: "Duct Height", unit: "mm" },
  equivalentDiameter: { label: "Equivalent Diameter", unit: "mm" },
  hydraulicDiameter: { label: "Hydraulic Diameter", unit: "mm" },
  velocityPressure: { label: "Velocity Pressure", unit: "Pa" },
  reynoldsNumber: { label: "Reynolds Number" },
  frictionFactor: { label: "Friction Factor" },
  frictionLoss: { label: "Friction Loss", unit: "Pa" },
  equalFriction: { label: "Equal Friction Rate", unit: "Pa/m" },
  dynamicPressure: { label: "Dynamic Pressure", unit: "Pa" },
  staticRegain: { label: "Static Regain", unit: "Pa" },
  roundDiameter: { label: "Equivalent Round Diameter", unit: "mm" },
  noiseLevel: { label: "Noise Level" },

  filterWidth: { label: "Filter Width", unit: "mm" },
  filterHeight: { label: "Filter Height", unit: "mm" },
  initialResistance: { label: "Initial Resistance", unit: "Pa" },
  finalResistance: { label: "Final Resistance", unit: "Pa" },
  pressureGrowth: { label: "Pressure Growth", unit: "Pa" },
  dustConcentration: { label: "Dust Concentration", unit: "kg/m³" },
  operatingHours: { label: "Operating Hours", unit: "hr/month" },
  filterEfficiency: { label: "Filter Efficiency", unit: "%" },
  mervRating: { label: "MERV Rating" },
  filterArea: { label: "Filter Area", unit: "m²" },
  actualFaceVelocity: { label: "Actual Face Velocity", unit: "m/s" },
  dustLoading: { label: "Dust Loading", unit: "kg" },
  dustHoldingCapacity: { label: "Dust Holding Capacity", unit: "kg" },
  filterLifeDays: { label: "Estimated Filter Life", unit: "days" },
  energyImpact: { label: "Energy Impact", unit: "kWh approx" },
  filterType: { label: "Filter Type" },
  cleanroomClass: { label: "Cleanroom Suitability" },
  velocityStatus: { label: "Velocity Status" },

  casingCost: { label: "Casing / Sheet Metal Cost", unit: "₹" },
  coilCost: { label: "Cooling Coil Cost", unit: "₹" },
  blowerCost: { label: "Blower Cost", unit: "₹" },
  motorCost: { label: "Motor Cost", unit: "₹" },
  filterCost: { label: "Filter Cost", unit: "₹" },
  damperCost: { label: "Damper Cost", unit: "₹" },
  electricalCost: { label: "Electrical Cost", unit: "₹" },
  labourCost: { label: "Labour Cost", unit: "₹" },
  packingTransportCost: { label: "Packing / Transport Cost", unit: "₹" },
  testingCost: { label: "Testing Cost", unit: "₹" },
  overheadPercent: { label: "Overhead", unit: "%" },
  profitPercent: { label: "Profit", unit: "%" },
  gstPercent: { label: "GST", unit: "%" },
  materialCost: { label: "Material Cost", unit: "₹" },
  manufacturingCost: { label: "Manufacturing Cost", unit: "₹" },
  directCost: { label: "Direct Cost", unit: "₹" },
  overheadAmount: { label: "Overhead Amount", unit: "₹" },
  costBeforeProfit: { label: "Cost Before Profit", unit: "₹" },
  profitAmount: { label: "Profit Amount", unit: "₹" },
  sellingPriceBeforeGST: { label: "Selling Price Before GST", unit: "₹" },
  gstAmount: { label: "GST Amount", unit: "₹" },
  finalSellingPrice: { label: "Final Selling Price", unit: "₹" },

  coolingTR: { label: "Cooling Capacity", unit: "TR" },
  baseLength: { label: "AHU Length", unit: "mm" },
  baseWidth: { label: "AHU Width", unit: "mm" },
  baseHeight: { label: "AHU Height", unit: "mm" },
  casingArea: { label: "Casing Area", unit: "m²" },
  insulationArea: { label: "Insulation Area", unit: "m²" },
  frameWeight: { label: "Frame Weight", unit: "kg" },
  sheetWeight: { label: "Sheet Weight", unit: "kg" },
  coolingLoadTR: { label: "Cooling Load", unit: "TR" },
  coilCapacityTR: { label: "Coil Capacity", unit: "TR" },
  blowerMotorKW: { label: "Blower Motor", unit: "kW" },
  ductSize: { label: "Duct Size", unit: "mm" }
};

export function humanizeKey(key = "") {
  return key
    .replace(/_/g, " ")
    .replace(/([A-Z])/g, " $1")
    .replace(/\s+/g, " ")
    .trim()
    .replace(/^./, (str) => str.toUpperCase());
}

export function getFieldMeta(key) {
  return FIELD_META[key] || { label: humanizeKey(key) };
}

export function formatFieldLabel(key) {
  const meta = getFieldMeta(key);
  return meta.unit ? `${meta.label} (${meta.unit})` : meta.label;
}

export function formatResultLabel(key) {
  return formatFieldLabel(key);
}
