import jsPDF from "jspdf";

function safe(value, fallback = "-") {
  if (value === null || value === undefined || value === "") return fallback;
  return value;
}

function money(value) {
  return `Rs. ${Number(value || 0).toFixed(0)}`;
}

function addPageIfNeeded(doc, y) {
  if (y > 275) {
    doc.addPage();
    return 20;
  }

  return y;
}

export function generateCompleteProjectPDF(project) {
  if (!project) {
    alert("Please run complete design first.");
    return;
  }

  const doc = new jsPDF("p", "mm", "a4");

  let y = 20;

  function title(text) {
    y = addPageIfNeeded(doc, y);
    doc.setFontSize(16);
    doc.setFont(undefined, "bold");
    doc.text(text, 15, y);
    y += 10;
  }

  function section(text) {
    y += 4;
    y = addPageIfNeeded(doc, y);
    doc.setFontSize(13);
    doc.setFont(undefined, "bold");
    doc.text(text, 15, y);
    y += 8;
  }

  function line(label, value) {
    y = addPageIfNeeded(doc, y);
    doc.setFontSize(10);
    doc.setFont(undefined, "normal");

    const text = `${label}: ${safe(value)}`;
    const split = doc.splitTextToSize(text, 175);

    doc.text(split, 18, y);
    y += split.length * 6;
  }

  function tableHeader(headers, widths) {
    y = addPageIfNeeded(doc, y);
    doc.setFontSize(9);
    doc.setFont(undefined, "bold");

    let x = 15;

    headers.forEach((h, i) => {
      doc.rect(x, y - 5, widths[i], 8);
      doc.text(String(h), x + 2, y);
      x += widths[i];
    });

    y += 8;
  }

  function tableRow(values, widths) {
    y = addPageIfNeeded(doc, y);
    doc.setFontSize(8);
    doc.setFont(undefined, "normal");

    let x = 15;

    values.forEach((v, i) => {
      doc.rect(x, y - 5, widths[i], 8);
      doc.text(String(safe(v)), x + 2, y);
      x += widths[i];
    });

    y += 8;
  }

  const auto = project.autoDesign;
  const fan = project.fanSelection;
  const filter = project.filterSelection;
  const coil = project.coilSelection;
  const pump = project.pumpSelection;
  const pressure = project.pressureLoss;

  /* COVER PAGE */

  doc.setFontSize(22);
  doc.setFont(undefined, "bold");
  doc.text("Apfel Globus Engineering OS", 15, 25);

  doc.setFontSize(13);
  doc.setFont(undefined, "normal");
  doc.text("Professional HVAC / AHU / Cleanroom Design Report", 15, 35);

  doc.setLineWidth(0.5);
  doc.line(15, 42, 195, 42);

  y = 55;

  line("Project Name", project.input.projectName || "Untitled Project");
  line("Client Name", project.input.clientName || "Client");
  line("Application", project.summary.application);
  line("Report Date", new Date().toLocaleString());
  line("Generated By", "Apfel Globus Engineering OS");

  y += 10;

  doc.setFontSize(11);
  doc.setFont(undefined, "bold");
  doc.text("Important Note", 15, y);
  y += 7;

  doc.setFontSize(10);
  doc.setFont(undefined, "normal");
  doc.text(
    doc.splitTextToSize(
      "This report is generated for engineering design assistance. Final design must be reviewed, validated, commissioned and approved by qualified HVAC / pharma cleanroom professionals before execution.",
      175
    ),
    15,
    y
  );

  doc.addPage();
  y = 20;

  /* DESIGN BASIS */

  title("1. Design Basis");

  line("Application", auto.designBasis.application);
  line("Cleanroom / HVAC Class", auto.designBasis.cleanroomClass);
  line("ACH", auto.designBasis.ach);
  line("Temperature", `${auto.designBasis.temperature} deg C`);
  line("Relative Humidity", `${auto.designBasis.rh}%`);
  line("Pressure", `+${auto.designBasis.pressure} Pa`);
  line("Filter Train", auto.designBasis.filterTrain);
  line("Fresh Air", `${auto.designBasis.freshAirPercent}%`);
  line("Exhaust", `${auto.designBasis.exhaustPercent}%`);
  line("Safety Factor", auto.designBasis.safetyFactor);

  section("Standards / References");
  auto.designBasis.standards.forEach((s, index) => {
    line(`Reference ${index + 1}`, s);
  });

  /* ROOM + AIRFLOW */

  title("2. Room and Airflow Calculation");

  line("Room Length", `${auto.room.length} m`);
  line("Room Width", `${auto.room.width} m`);
  line("Room Height", `${auto.room.height} m`);
  line("Room Area", `${auto.room.area.toFixed(2)} m2`);
  line("Room Volume", `${auto.room.volume.toFixed(2)} m3`);
  line("Supply Airflow", `${auto.airflow.supplyCMH.toFixed(0)} CMH`);
  line("Fresh Air", `${auto.airflow.freshAirCMH.toFixed(0)} CMH`);
  line("Return Air", `${auto.airflow.returnAirCMH.toFixed(0)} CMH`);
  line("Exhaust Air", `${auto.airflow.exhaustCMH.toFixed(0)} CMH`);

  /* LOAD */

  title("3. Heat Load and Psychrometric Summary");

  line("People Load", `${auto.load.peopleLoadW.toFixed(0)} W`);
  line("Lighting Load", `${auto.load.lightingLoadW.toFixed(0)} W`);
  line("Equipment Load", `${auto.load.equipmentLoadW.toFixed(0)} W`);
  line("Total Sensible Load", `${auto.load.totalSensibleW.toFixed(0)} W`);
  line("Cooling Load", `${auto.coil.capacityTR.toFixed(2)} TR`);
  line("Total Cooling", `${auto.psychrometrics.totalCoolingKW.toFixed(2)} kW`);
  line("Sensible Cooling", `${auto.psychrometrics.sensibleCoolingKW.toFixed(2)} kW`);
  line("Latent Cooling", `${auto.psychrometrics.latentCoolingKW.toFixed(2)} kW`);
  line("Moisture Removal", `${auto.psychrometrics.moistureRemovalKgHr.toFixed(2)} kg/hr`);

  /* EQUIPMENT */

  title("4. Equipment Selection");

  section("Fan Selection");
  line("Fan Model", fan.selectedFan.model);
  line("Fan Type", fan.selectedFan.type);
  line("Fan Airflow Rating", `${fan.selectedFan.airflowCMH} CMH`);
  line("Fan Pressure Rating", `${fan.selectedFan.pressurePa} Pa`);
  line("Fan Motor", `${fan.selectedFan.motorHP} HP`);
  line("Fan Efficiency", `${fan.selectedFan.efficiency}%`);
  line("Fan RPM", fan.selectedFan.rpm);
  line("Impeller Diameter", `${fan.selectedFan.impellerDiaMM} mm`);
  line("Noise", `${fan.selectedFan.noiseDB} dB`);

  section("Filter Selection");

  tableHeader(
    ["Stage", "Grade", "Qty", "Size", "Initial Pa", "Final Pa"],
    [35, 25, 20, 50, 30, 30]
  );

  filter.selectedFilters.forEach((f) => {
    tableRow(
      [
        f.type,
        f.grade,
        f.quantity,
        f.size,
        f.totalInitialPressurePa,
        f.totalFinalPressurePa,
      ],
      [35, 25, 20, 50, 30, 30]
    );
  });

  section("Coil Selection");
  line("Coil Model", coil.selectedCoil.model);
  line("Coil Capacity", `${coil.selectedCoil.capacityTR} TR`);
  line("Rows", coil.selectedCoil.rows);
  line("Face Size", `${coil.selectedCoil.faceWidthMM} x ${coil.selectedCoil.faceHeightMM} mm`);
  line("Air Pressure Drop", `${coil.selectedCoil.airPressureDropPa} Pa`);
  line("Water Pressure Drop", `${coil.selectedCoil.waterPressureDropKPa} kPa`);
  line("CHW Flow", `${coil.chilledWater.flowLPM} LPM`);
  line("Pipe Size", coil.chilledWater.pipeSize);
  line("Valve Size", coil.chilledWater.valveSize);

  section("Pump Selection");
  line("Pump Model", pump.selectedPump.model);
  line("Pump Type", pump.selectedPump.type);
  line("Flow", `${pump.selectedPump.flowLPM} LPM`);
  line("Head", `${pump.selectedPump.headM} m`);
  line("Motor", `${pump.selectedPump.motorHP} HP`);
  line("Efficiency", `${pump.selectedPump.efficiency}%`);
  line("RPM", pump.selectedPump.rpm);
  line("Suction / Discharge", `${pump.selectedPump.suctionSize} / ${pump.selectedPump.dischargeSize}`);

  /* PRESSURE */

  title("5. Pressure Loss Breakdown");

  tableHeader(["Section", "Pressure Pa"], [90, 50]);

  pressure.breakdown.forEach((p) => {
    tableRow([p.item, p.pressure], [90, 50]);
  });

  line("Total Static Pressure", `${pressure.totalStaticPressure.toFixed(0)} Pa`);
  line("Recommended Fan Pressure", `${pressure.recommendedFanPressure} Pa`);

  /* BOM */

  title("6. BOM and Commercial Summary");

  tableHeader(["Item", "Specification", "Qty", "Rate"], [40, 85, 20, 35]);

  auto.bom.items.forEach((item) => {
    tableRow(
      [
        item.item,
        String(item.specification).slice(0, 45),
        item.qty,
        money(item.rate),
      ],
      [40, 85, 20, 35]
    );
  });

  section("Cost Summary");
  line("Material Cost", money(auto.bom.material));
  line("Fabrication", money(auto.bom.fabrication));
  line("Installation", money(auto.bom.installation));
  line("Overhead", money(auto.bom.overhead));
  line("Profit", money(auto.bom.profit));
  line("Estimated Selling Price", money(auto.bom.selling));

  /* VALIDATION */

  title("7. Validation and Warnings");

  line("Validation Requirement", auto.designBasis.validation);

  if (project.warnings.length > 0) {
    project.warnings.forEach((w, index) => {
      line(`Warning ${index + 1}`, w);
    });
  } else {
    line("Warnings", "No major warnings generated.");
  }

  section("Final Disclaimer");
  line(
    "Disclaimer",
    "This software output is preliminary engineering assistance only. Final selection must be confirmed using manufacturer datasheets, site measurements, approved URS, GMP requirements, commissioning results and qualified engineer approval."
  );

  doc.save("Apfel_Globus_Complete_HVAC_AHU_Report.pdf");
}